(list) @form
(list_binding) @form
(sequence) @form
(sequence_binding) @form
(sequence_arguments) @form
(table) @form
(table_binding) @form
(table_metadata) @form
(case_catch) @form
(case_form) @form
(case_guard) @form
(match_form) @form
(case_try_form) @form
(match_try_form) @form
(if_form) @form
(fn_form) @form
(lambda_form) @form
(macro_form) @form
(hashfn_form) @form
(each_form) @form
(collect_form) @form
(icollect_form) @form
(accumulate_form) @form
(for_form) @form
(fcollect_form) @form
(faccumulate_form) @form
(local_form) @form
(var_form) @form
(global_form) @form
(set_form) @form
(let_form) @form
(let_vars) @form
(import_macros_form) @form
(quote_form) @form
(unquote_form) @form
